name: Unit Tests

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env
        run: echo "ENV=test" >> $GITHUB_ENV

      - name: Install pdm
        run: pip install pdm

      - name: Install project dependencies
        run: pdm install

      - name: Install playwright
        run: pdm run playwright install

      - name: Run tests
        run: PYTHONPATH=. pdm run pytest -v -ra api/backend/tests

  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-cypress-tests
        with:
          openai_key: ${{ secrets.OPENAI_KEY }}

  failure:
    needs: cypress-tests
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check container logs
        run: |
          echo "Checking scraperr_api container logs..."
          docker logs scraperr_api || true

  success-message:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - cypress-tests
    steps:
      - name: Send Discord Message
        uses: jaypyles/discord-webhook-action@v1.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Scraperr Successfully Passed Tests"
          username: "Scraperr CI"
          embed-title: "âœ… Deployment Status"
          embed-description: "Scraperr successfully passed all tests."
          embed-color: 3066993 # Green
          embed-footer-text: "Scraperr CI"
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
